Description: >
  Abdallah Kenawy / Udacity
  create IAM role to be attached to ec2 scalling group.

Parameters:

  EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

Resources:
  Us3Role:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: UdacityS3ReadOnlyEC2
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 's3:GetObject'
                Resource: 'arn:aws:s3:::udacity-demo-1/udacity.zip'


Outputs: 

    VPC: 
        Description: A reference to the created iamrole
        Value: !Ref Us3Role
        Export:
          Name: !Sub ${EnvironmentName}-IAMrole